name: Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" | tr -d '\r' > serviceAccountKey.json
          gcloud auth activate-service-account --key-file=serviceAccountKey.json
          gcloud config set project your-project-id

      - name: Install app dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
